# -*- coding: utf-8 -*-
"""Brain tumor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTzsSRovlkjrT6sZ53dbCHOxU1WMbUtD
"""

# Import Libraries
import streamlit as st
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image

import tensorflow as tf

#Import Libraries
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Conv2D

from tensorflow.keras.layers import MaxPooling2D

from tensorflow.keras.layers import Flatten

from tensorflow.keras.layers import Dense

from tensorflow.keras.layers import Dropout

import matplotlib.pyplot as plt

import numpy as np

#Data Preprocessing
# Image Augmentation
train_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    zoom_range=0.2,

    horizontal_flip=True,

    validation_split=0.2

)

#Mount the Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Define Paths
train_path = "/content/drive/MyDrive/Brain_Tumor/Training"
test_path = "/content/drive/MyDrive/Brain_Tumor/Testing"

#Create ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

#Training Generator
train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

import os

drive_brain_tumor_path = '/content/drive/MyDrive/Brain_Tumor'

if os.path.exists(drive_brain_tumor_path):
    print(f"Contents of '{drive_brain_tumor_path}':")
    for item in os.listdir(drive_brain_tumor_path):
        print(item)
else:
    print(f"The directory '{drive_brain_tumor_path}' does not exist in your Google Drive. Please ensure the 'Brain_Tumor' folder is directly in 'My Drive'.")

import os

my_drive_path = '/content/drive/MyDrive'

if os.path.exists(my_drive_path):
    print(f"Contents of '{my_drive_path}':")
    for item in os.listdir(my_drive_path):
        print(item)
else:
    print(f"The directory '{my_drive_path}' does not exist. This indicates an issue with the Google Drive mount.")

"""### Expected Folder Structure for `flow_from_directory`

For `flow_from_directory` to work correctly, your data should be structured like this:

```
Brain_Tumor/
├── Training/
│   ├── class1/          (e.g., 'glioma', 'meningioma')
│   │   ├── image1.jpg
│   │   ├── image2.png
│   │   └── ...
│   ├── class2/
│   │   ├── imageA.jpg
│   │   └── ...
│   └── ...
└── Testing/
    ├── class1/
    │   ├── test_image1.jpg
    │   └── ...
    ├── class2/
    │   ├── test_imageA.jpg
    │   └── ...
    └── ...
```

If your `Training` and `Testing` folders are directly inside `Brain_Tumor`, but they don't contain these class-specific subfolders with images, then `flow_from_directory` will report 'Found 0 images belonging to 0 classes', which is what you're currently seeing.

Please verify that your folders have this structure. I can provide code to list the contents of your `Training` and `Testing` subfolders if you'd like.
"""

import os

# Verify the contents of the Training directory
print(f"\nContents of '{train_path}':")
if os.path.exists(train_path):
    items = os.listdir(train_path)
    if items:
        for item in items:
            print(item)
    else:
        print("The 'Training' directory is empty.")
else:
    print("The 'Training' directory does not exist.")

# Verify the contents of the Testing directory
print(f"\nContents of '{test_path}':")
if os.path.exists(test_path):
    items = os.listdir(test_path)
    if items:
        for item in items:
            print(item)
    else:
        print("The 'Testing' directory is empty.")
else:
    print("The 'Testing' directory does not exist.")

import os

# Function to list contents of a directory with a limit
def list_dir_contents(path, limit=5):
    if os.path.exists(path):
        items = os.listdir(path)
        if items:
            print(f"Contents of '{path}' (first {limit} items):")
            for i, item in enumerate(items):
                if i < limit:
                    print(f"- {item}")
                else:
                    print(f"- ... ({len(items) - limit} more items)")
                    break
        else:
            print(f"The directory '{path}' is empty.")
    else:
        print(f"The directory '{path}' does not exist.")

# Check Training directory
print("\n--- Verifying Training Directory ---")
list_dir_contents(train_path)

# If Training directory exists and has contents, check one of its subfolders (if any)
if os.path.exists(train_path) and os.listdir(train_path):
    first_training_subfolder = os.path.join(train_path, os.listdir(train_path)[0])
    if os.path.isdir(first_training_subfolder):
        print(f"\n--- Verifying contents of a sample class folder in Training ({os.path.basename(first_training_subfolder)}) ---")
        list_dir_contents(first_training_subfolder)
    else:
        print(f"\n'{os.path.basename(first_training_subfolder)}' in Training is not a folder. Expected class subfolders.")

# Check Testing directory
print("\n--- Verifying Testing Directory ---")
list_dir_contents(test_path)

# If Testing directory exists and has contents, check one of its subfolders (if any)
if os.path.exists(test_path) and os.listdir(test_path):
    first_testing_subfolder = os.path.join(test_path, os.listdir(test_path)[0])
    if os.path.isdir(first_testing_subfolder):
        print(f"\n--- Verifying contents of a sample class folder in Testing ({os.path.basename(first_testing_subfolder)}) ---")
        list_dir_contents(first_testing_subfolder)
    else:
        print(f"\n'{os.path.basename(first_testing_subfolder)}' in Testing is not a folder. Expected class subfolders.")

import os

# Function to list contents of a directory with a limit (re-using the one defined before)
def list_dir_contents(path, limit=5):
    if os.path.exists(path):
        items = os.listdir(path)
        if items:
            print(f"Contents of '{path}' (first {limit} items):")
            for i, item in enumerate(items):
                if i < limit:
                    print(f"- {item}")
                else:
                    print(f"- ... ({len(items) - limit} more items)")
                    break
        else:
            print(f"The directory '{path}' is empty.")
    else:
        print(f"The directory '{path}' does not exist.")

print("\n--- Verifying contents of each class subfolder in Training ---")
if os.path.exists(train_path):
    class_subfolders = [os.path.join(train_path, f) for f in os.listdir(train_path) if os.path.isdir(os.path.join(train_path, f))]
    if class_subfolders:
        for class_folder in class_subfolders:
            print(f"\nChecking: {class_folder}")
            list_dir_contents(class_folder)
    else:
        print("No class subfolders found in the Training directory.")
else:
    print("The Training directory does not exist.")

import os

# Function to list contents of a directory with a limit (re-using the one defined before)
def list_dir_contents(path, limit=5):
    if os.path.exists(path):
        items = os.listdir(path)
        if items:
            print(f"Contents of '{path}' (first {limit} items):")
            for i, item in enumerate(items):
                if i < limit:
                    print(f"- {item}")
                else:
                    print(f"- ... ({len(items) - limit} more items)")
                    break
        else:
            print(f"The directory '{path}' is empty.")
    else:
        print(f"The directory '{path}' does not exist.")

print("\n--- Verifying contents of each class subfolder in Testing ---")
if os.path.exists(test_path):
    class_subfolders = [os.path.join(test_path, f) for f in os.listdir(test_path) if os.path.isdir(os.path.join(test_path, f))]
    if class_subfolders:
        for class_folder in class_subfolders:
            print(f"\nChecking: {class_folder}")
            list_dir_contents(class_folder)
    else:
        print("No class subfolders found in the Testing directory.")
else:
    print("The Testing directory does not exist.")

"""If the previous cell outputs show that your class folders now contain images, please re-run the `train_generator` and `test_generator` cells (cells `LgbkEcSIb0Qj` and `fsu7fUG4b3FY`) to load the data."""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

import os

print(os.listdir("/content/drive/MyDrive/Brain_Tumor"))
print(os.listdir(train_path))

import os

print(os.listdir("/content/drive/MyDrive/Brain_Tumor"))
print(os.listdir(train_path))

train_generator = train_datagen.flow_from_directory(

    train_path,

    target_size=(224,224),

    batch_size=32,

    class_mode="categorical",

    subset="training"

)

validation_generator = train_datagen.flow_from_directory(

    test_path,

    target_size=(224,224),

    batch_size=32,

    class_mode="categorical",

    subset="validation"

)

print(train_generator.class_indices)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

#CNN model
# Build CNN
model = Sequential()

model.add(

Conv2D(

32,

(3,3),

activation="relu",

input_shape=(224,224,3)

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(

Conv2D(

64,

(3,3),

activation="relu"

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(

Conv2D(

128,

(3,3),

activation="relu"

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(128,activation="relu"))

model.add(Dropout(0.5))

model.add(Dense(4,activation="softmax"))

model.summary()

# Compile
model.compile(

optimizer="adam",

loss="categorical_crossentropy",

metrics=["accuracy"]

)

# Train
history = model.fit(

train_generator,

epochs=10,

validation_data=validation_generator

)

import matplotlib.pyplot as plt

#Model Performance
# Plot Accuracy
if 'history' in locals() and history is not None:
    plt.plot(history.history["accuracy"])
    plt.plot(history.history["val_accuracy"])
    plt.legend(["Train","Validation"])
    plt.show()
else:
    print("Error: 'history' object not found. Please ensure the model training cell (cell vHxMiRJXfp2e) was executed successfully.")

import matplotlib.pyplot as plt

# Plot Accuracy
if 'history' in locals() and history is not None:
    plt.plot(history.history["accuracy"])
    plt.plot(history.history["val_accuracy"])
    plt.legend(["Train","Validation"])
    plt.show()
else:
    print("Error: 'history' object not found. Please ensure the model training cell (cell vHxMiRJXfp2e) was executed successfully.")

plt.plot(history.history["loss"])

plt.plot(history.history["val_loss"])

plt.legend(["Train","Validation"])

plt.show()

import matplotlib.pyplot as plt

# Check if history exists in memory
if 'history' in globals() or 'history' in locals():
    # Setup a 1x2 subplot figure
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    # 1. Accuracy Plot
    if 'accuracy' in history.history:
        axes[0].plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
        axes[0].plot(history.history['val_accuracy'], label='Val Accuracy', linewidth=2)
        axes[0].set_title('Model Accuracy')
        axes[0].set_xlabel('Epoch')
        axes[0].set_ylabel('Accuracy')
        axes[0].legend()
        axes[0].grid(True)

    # 2. Loss Plot
    if 'loss' in history.history:
        axes[1].plot(history.history['loss'], label='Train Loss', linewidth=2)
        axes[1].plot(history.history['val_loss'], label='Val Loss', linewidth=2)
        axes[1].set_title('Model Loss')
        axes[1].set_xlabel('Epoch')
        axes[1].set_ylabel('Loss')
        axes[1].legend()
        axes[1].grid(True)

    plt.tight_layout()
    plt.show()
else:
    print("⚠️ Error: 'history' object not found in memory.")
    print("Please go back and run the cell with `history = model.fit(...)` first.")

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

loss,accuracy=model.evaluate(validation_generator)

print(accuracy)

model.save("/content/drive/MyDrive/brain_tumor_model.keras")

# Load Model
from tensorflow.keras.models import load_model

model=load_model("/content/drive/MyDrive/brain_tumor_model.keras")

from tensorflow.keras.preprocessing import image

img=image.load_img(

"/content/drive/MyDrive/Brain_Tumor/Training/pituitary/Tr-pi_1367.jpg",

target_size=(224,224)

)

img=image.img_to_array(img)

img=img/255

img=np.expand_dims(img,axis=0)

prediction=model.predict(img)

classes=["Glioma",

"Meningioma",

"No Tumor",

"Pituitary"]

print(classes[np.argmax(prediction)])

import streamlit as st

uploaded_file = st.file_uploader(

"Upload MRI",

type=["jpg","png","jpeg"]

)

if st.button("Predict"):

    prediction=model.predict(img)

    st.success(

    classes[np.argmax(prediction)]

    )

confidence=np.max(prediction)*100

st.write(

f"Confidence : {confidence:.2f}%"

)